inherit_gem:
  rubocop-discourse-base:
    - stree-compat.yml
    - rubocop-rspec.yml

AllCops:
  TargetRubyVersion: "3.4"
  NewCops: enable

Style/HashSyntax:
  EnforcedShorthandSyntax: always

Style/Send:
  Enabled: true

RSpec/DescribeClass:
  Exclude:
    - spec/integration/**/*