name: CI
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*
  schedule:
    - cron: '0 0 15 * *'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '2.6'
          - '2.7'
          - '3.0'
          - 'head'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run RSpec and Rubocop
        run: bundle exec rake

  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release Gem
        uses: discourse/publish-rubygems-action@v2-beta
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
          GIT_EMAIL: team@discourse.org
          GIT_NAME: discoursebot
