name: CI
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0'
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop

      - name: Check Ruby formatting with Syntax Tree
        run: bundle exec stree check Gemfile Rakefile *.gemspec "lib/**/*.rb" "spec/**/*.rb"

  verify-fixtures:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0'
          bundler-cache: true
      - run: tar --version | grep "GNU tar"
      - run: bundle exec rake fixtures:verify

  unit-tests:
    runs-on: ubuntu-latest
    name: Unit tests - Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: ['3.2', '3.3', '3.4', '4.0']

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run unit tests
        run: bundle exec rake unit

  integration-tests:
    runs-on: ${{ matrix.os }}
    name: Integration - ${{ matrix.os }} Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        ruby: ['3.2', '3.3', '3.4', '4.0']

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install GNU tar (macOS)
        run: brew install gnu-tar
        if: runner.os == 'macOS'
      - name: Verify GNU tar available
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            gtar --version | grep "GNU tar"
          else
            tar --version | grep "GNU tar"
          fi
      - name: Run integration tests
        run: bundle exec rake integration
        env:
          CI: true

  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [lint, verify-fixtures, unit-tests, integration-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Release Gem
        uses: discourse/publish-rubygems-action@v3
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
          GIT_EMAIL: team@discourse.org
          GIT_NAME: discoursebot
